baseURL: "https://jamesptran.netlify.app"
languageCode: "en-us"
title: "Phuc Tran"
theme: hugo-profile

Paginate: 3
disqusShortname: jamesptran96
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Phuc Tran"
  description: About myself
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Phuc Tran."
    # subtitle: "I am a full-stack software engineer"
    content: "I am a full-stack software developer with a passion for backend and mobile app development. I have background in computer science and economics. I am currently working as a software engineer at Amazon near Thousand Oaks, CA."
    image: /images/profile.jpg
    button:
      enable: true
      name: "Resume"
      url: "/resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jamesptran
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/phucjtran
        - icon: fab fa-instagram
          url: https://www.instagram.com/jamesptran96
        - icon: fab fa-facebook
          url: https://www.facebook.com/jamesptran96
#       customIcons:
#         - icon: /fav.png
#           url: "https://example.com"


  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Amazon"
        companyUrl: "https://aws.amazon.com/"
        date: "Jul 2022 - present"
        content: |
          - Developing applications for client from scratch.
          - Designing and matching the client requests.

      - job: "Software Engineer in Test"
        company: "Verizon"
        companyUrl: "https://www.verizon.com"
        date: "Jul 2018 - Aug 2020"
        content: |
          - Developed and maintained an embedded system simulator for server scalability tests to simulate complex device behavior for up to 200,000 devices using both MQTT and LWM2M communication protocols.
          - Maintained, monitored, and improved test automation, and the CI/CD pipeline ran through Jenkins automation.
          - Debugged and resolved bugs in a full-stack microservice application with Apache Kafka, AWS Lambda, Cassandra, Aurora, Spark, and other custom-built services.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Computer Science"
        school:
          name: "University of California, Irvine"
          # url: "https://example.org"
        date: "2020 - 2022"
        GPA: "3.97 out of 4.0"
        content: |-
          During this period I worked on various paid research and development project for professors and studies at UC Irvine. Some highlights include.
          - Developed new features for ZotCare, an IoT platform that is used for aggregating watch data by 20+ different graduate studies across different disciplines.
          - Developed a specialized native iOS application to serve as a front end for ZotCare and Empatica E4 device for a psychology study.
          - Spearheaded the initial development effort for Personicle, a multimodal open-source platform to monitor health biomarkers for building disease models and data aggregation.
      - title: "Bachelor of Arts in Computer Science"
        school:
          name: "Earlham College"
          # url: "https://example.org"
        date: "2014 - 2018"
        GPA: "3.8 out of 4.0"
#         content: |-
#           I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
#           - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
#           - Face mask detection using a single convolutional neural network.

#           Extracurricular Activities
#             - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
#             - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
#         featuredLink:
#           enable: true
#           name: "My academic record"
#           url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: ARShow
        content: An augmented reality application to render furnitures realistically in your room.
        image: /images/projects/profile.png
        featured:
          name: Github
          link: https://github.com/jamesptran/ARShow
        badges:
          - "Swift"
          - "ARKit"
        links:
          - icon: fab fa-github
            url: https://github.com/jamesptran/ARShow

      - title: Dark Space
        content: A 2D space shooter arcade game which featured 9 different levels and 6 different enemy types.
        image: /images/projects/converter.jpg
        featured:
          name: AppAdvice
          link: https://appadvice.com/app/dark-space-chess-battalion/1309936967
        badges:
          - "Swift"
          - "SpriteKit"
        links:
          - icon: fab fa-github
            url: https://github.com/jamesptran/DarkSpace

      - title: E4Link Empatica Research App
        content: An application which collects data from Empatica E4 devices and sync it with backend server.
        image: /images/projects/profile2.jpg
#         featured:
#           name: Demo V2
#           link: https://hugo-profile-2.netlify.app
        badges:
          - "Swift"
          - "Python"
          - "MongoDB"
        links:
          - icon: fab fa-github
            url: https://github.com/amyxjhuang/research-app

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Just send me an email and I’ll try my best to get back to you!
    email: jamesptran96@gmail.com
    btnName: Email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/jamesptran
      linkedin: https://www.linkedin.com/in/phucjtran
      instagram: https://www.instagram.com/jamesptran96
      facebook: https://www.facebook.com/jamesptran96
