baseURL: "https://jamesptran.netlify.app"
languageCode: "en-us"
title: "Phuc Tran"
theme: hugo-profile

Paginate: 3
disqusShortname: jamesptran96
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Phuc Tran"
  description: About myself
  # staticPath: ""  # The path to serve the static files from
  # favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    # intro: "Hi, my name is"
    title: "Phuc Tran."
    subtitle: "I am a full-stack software engineer"
    content: ""
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "/resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jamesptran
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/phucjtran/
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: false
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a full-stack software developer with a passion for iOS development. I have a background in computer science and economics. I am currently working as a software developer at Amazon near Los Angeles, CA. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Swift"
        - "Java"
        - "Python"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Amazon"
        companyUrl: "https://aws.amazon.com/"
        date: "Jul 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        # content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."
        info:
          enable: true
          content: I am working as a software engineer for Amazon.
        content: |
          - Developing applications for client from scratch.
          - Designing and matching the client requests.

      - job: "Software Engineer in Test"
        company: "Verizon"
        companyUrl: "https://www.verizon.com"
        date: "Jul 2018 - Aug 2020"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I worked as an SDET for more than one year in Verizon.
        content: |
          - Developed and maintained an embedded system simulator for server scalability tests to simulate complex device behavior for up to 200,000 devices using both MQTT and LWM2M communication protocols.
          - Maintained, monitored, and improved test automation, and the CI/CD pipeline ran through Jenkins automation.
          - Debugged and resolved bugs in a full-stack microservice application with Apache Kafka, AWS Lambda, Cassandra, Aurora, Spark, and other custom-built services.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Computer Science"
        school:
          name: "University of California, Irvine"
          # url: "https://example.org"
        date: "2020 - 2022"
        GPA: "3.97 out of 4.0"
        content: |-
          During this period I worked on various paid research and development project for professors and studies at UC Irvine. Some highlights include.
          - Developed new features for ZotCare, an IoT platform that is used for aggregating watch data by 20+ different graduate studies across different disciplines.
          - Developed a specialized native iOS application to serve as a front end for ZotCare and Empatica E4 device for a psychology study.
          - Spearheaded the initial development effort for Personicle, a multimodal open-source platform to monitor health biomarkers for building disease models and data aggregation.
      - title: "Bachelor of Arts in Computer Science"
        school:
          name: "Earlham College"
          # url: "https://example.org"
        date: "2014 - 2018"
        GPA: "3.8 out of 4.0"
#         content: |-
#           I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
#           - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
#           - Face mask detection using a single convolutional neural network.

#           Extracurricular Activities
#             - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
#             - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
#         featuredLink:
#           enable: true
#           name: "My academic record"
#           url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
#     content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: jamesptran96@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/jamesptran
      linkedin: https://www.linkedin.com/in/phucjtran/
